version: '3.9'

services: 
  mongo_db:
    container_name: localhost
    image: mongo:6.0
    restart: always
    ports:
      - 2717:27017
    volumes:
      - mongo_db_volume:/data/db
    
  redis:
    container_name: redis
    image: redis:latest
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data

  nodejs_app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mongo_db
      - redis
    env_file:
      - .env
    ports:
      - 3000:3000
    volumes:
      - .:/akhilphenom/backend

volumes:
  mongo_db_volume: {}
  redis_data: {}

    